# Generated by Django 5.0.6 on 2024-07-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_remove_attendance_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
