# Generated by Django 5.0.6 on 2024-06-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_remove_department_history_department_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('LUNCH BREAK', 'LUNCH BREAK'), ('SHORT BREAK', 'SHORT BREAK'), ('LEAVE', 'LEAVE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp352', max_length=70),
        ),
    ]
