# Generated by Django 5.0.6 on 2024-07-26 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_attendance_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
