# Generated by Django 5.0.6 on 2024-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_remove_employee_address_remove_employee_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp762', max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='mng_id',
            field=models.CharField(default='mng948', max_length=70),
        ),
    ]
