# Generated by Django 5.0.6 on 2024-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_remove_employee_department_remove_user_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='emp929', max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='mng_id',
            field=models.CharField(default='mng318', max_length=70),
        ),
    ]
