# Generated by Django 5.0.6 on 2024-08-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_location_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imei',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
