# Generated by Django 5.0.6 on 2024-08-21 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_user_imei'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.location'),
        ),
    ]
