# Generated by Django 5.0.6 on 2024-06-05 17:32

import hrms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_alter_user_emp_id_alter_user_mng_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default=hrms.models.generate_emp_id, editable=False, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mng_id',
            field=models.CharField(default=hrms.models.generate_mng_id, editable=False, max_length=70, unique=True),
        ),
    ]
