# Generated by Django 5.0.6 on 2024-09-13 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_device_attendance_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='device',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.accountmanager'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.admin'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='human_resource_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.humanresourcemanager'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='imei',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.device'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
