# Generated by Django 5.0.6 on 2024-06-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_attendance_latitude_attendance_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
