# Generated by Django 5.0.6 on 2024-10-04 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_remove_attendance_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='imei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.device'),
        ),
    ]
