# Generated by Django 5.0.6 on 2024-10-07 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_alter_attendance_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='hrms.accountmanager'),
        ),
    ]
