# Generated by Django 5.0.6 on 2024-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clockin_privileges',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('employee', 'Employee'), ('manager', 'Manager'), ('client', 'Client'), ('can_clockin_anywhere', 'Can clock in from anywhere'), ('no_clockin_privileges', 'Cannot clock in from anywhere'), ('no_role', 'No role')], default='no_clockin_privileges', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(editable=False, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mng_id',
            field=models.CharField(editable=False, max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('employee', 'Employee'), ('manager', 'Manager'), ('client', 'Client'), ('can_clockin_anywhere', 'Can clock in from anywhere'), ('no_clockin_privileges', 'Cannot clock in from anywhere'), ('no_role', 'No role')], default='no_role', max_length=255),
        ),
    ]
