# Generated by Django 5.0.6 on 2024-11-15 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_alter_client_account_manager_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client',
        ),
        migrations.AlterField(
            model_name='user',
            name='assigned_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.department'),
        ),
    ]
