# Generated by Django 5.0.6 on 2024-11-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_remove_contract_client_alter_user_assigned_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='id_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
