# Generated by Django 5.0.6 on 2024-11-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0015_contract_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
