# Generated by Django 5.0.6 on 2024-11-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_contract_current_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='current_date',
        ),
    ]
