# Generated by Django 5.0.6 on 2024-11-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_remove_contract_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
