# Generated by Django 5.0.6 on 2024-06-17 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.admin'),
        ),
    ]
