# Generated by Django 5.0.6 on 2024-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0018_attendance_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emergency',
            new_name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
