# Generated by Django 5.0.6 on 2024-12-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0019_alter_contract_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='employee',
            new_name='user',
        ),
    ]
