# Generated by Django 5.0.6 on 2024-12-03 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_rename_employee_contract_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employee'),
        ),
    ]
