# Generated by Django 5.0.6 on 2024-06-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0022_alter_user_role_accountmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
