# Generated by Django 5.0.6 on 2024-06-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0028_user_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='client',
        ),
    ]
