# Generated by Django 5.0.6 on 2024-06-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0029_remove_employee_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='account_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.accountmanager'),
        ),
    ]
