# Generated by Django 5.0.6 on 2024-06-27 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0030_attendance_account_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('employee', 'Employee'), ('account_manager', 'AccountManager'), ('human_resource_manager', 'Human resource manager'), ('client', 'Client'), ('can_clockin_anywhere', 'Can clock in from anywhere'), ('Within the organization', 'Cannot clock in from anywhere'), ('no_role', 'No role')], default='no_role', max_length=255),
        ),
        migrations.CreateModel(
            name='HumanResourceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('human_resource_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
