# Generated by Django 5.0.6 on 2024-06-28 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0031_alter_user_role_humanresourcemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='human_resource_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.humanresourcemanager'),
        ),
    ]
