# Generated by Django 5.0.6 on 2024-11-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracttemplate',
            old_name='template_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='contracttemplate',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GeneratedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_content', models.TextField()),
                ('placeholder_data', models.JSONField()),
                ('recipient_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract_management.contracttemplate')),
            ],
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
