# Generated by Django 5.0.6 on 2024-11-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0002_rename_template_content_contracttemplate_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contracttemplate',
            old_name='content',
            new_name='template_content',
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='placeholders',
            field=models.ManyToManyField(to='contract_management.placeholder'),
        ),
        migrations.DeleteModel(
            name='GeneratedContract',
        ),
    ]
