# Generated by Django 5.0.6 on 2024-11-28 07:36

import jsignature.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0004_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('signature', jsignature.fields.JSignatureField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
