# Generated by Django 5.0.6 on 2024-12-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0007_remove_contracttemplate_user_contract_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='admin_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='user_signed',
            field=models.BooleanField(default=False),
        ),
    ]
