# Generated by Django 5.0.6 on 2024-12-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0008_contract_admin_signed_contract_user_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
