# Generated by Django 5.0.6 on 2024-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0009_contract_email_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contract',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
