# Generated by Django 5.0.6 on 2024-12-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0010_alter_contract_options_contract_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
    ]
