# Generated by Django 5.0.6 on 2024-12-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_management', '0011_alter_contract_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='initials',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
